const fs = require('fs');
const path = require('path');

const { Compiler, CompilerOptions } = require('inkjs/full');

const projectRoot = path.resolve(__dirname, '..');
const storiesRoot = path.join(projectRoot, 'src', 'story');
const generatedRoot = path.join(storiesRoot, 'generated');
const storyImagesRoot = path.join(projectRoot, 'assets', 'story-images');
const generatedStoryImagesPath = path.join(projectRoot, 'src', 'game', 'generated', 'story-images.ts');
const imageExtensions = new Set(['.avif', '.gif', '.jpg', '.jpeg', '.png', '.webp']);

const INK_WARNING = 1;
const INK_ERROR = 2;

main();

function main() {
  const storyFiles = findInkFiles(storiesRoot);

  if (storyFiles.length === 0) {
    console.error(`No .ink files found under ${path.relative(projectRoot, storiesRoot)}`);
    process.exit(1);
  }

  for (const storyFile of storyFiles) {
    compileStoryFile(storyFile);
  }

  generateStoryImageCatalog(storyFiles);
}

function findInkFiles(directoryPath) {
  const entries = fs.readdirSync(directoryPath, { withFileTypes: true });
  const storyFiles = [];

  for (const entry of entries) {
    const entryPath = path.join(directoryPath, entry.name);

    if (entry.isDirectory()) {
      if (entryPath === generatedRoot) {
        continue;
      }

      storyFiles.push(...findInkFiles(entryPath));
      continue;
    }

    if (entry.isFile() && entry.name.endsWith('.ink')) {
      storyFiles.push(entryPath);
    }
  }

  return storyFiles.sort();
}

function compileStoryFile(inputPath) {
  const inputSource = fs.readFileSync(inputPath, 'utf8');
  const warnings = [];
  const errors = [];

  const compiler = new Compiler(
    inputSource,
    new CompilerOptions(inputPath, [], false, (message, type) => {
      if (type === INK_WARNING) {
        warnings.push(message);
        return;
      }

      if (type === INK_ERROR) {
        errors.push(message);
      }
    }, createFileHandler())
  );

  let runtimeStory;
  try {
    runtimeStory = compiler.Compile();
  } catch (error) {
    if (error instanceof Error && error.message === 'Compilation failed.') {
      reportFailure(inputPath, errors);
      return;
    }

    throw error;
  }

  if (errors.length > 0) {
    reportFailure(inputPath, errors);
    return;
  }

  const compiledJson = runtimeStory.ToJson();
  if (typeof compiledJson !== 'string') {
    throw new Error(`Ink compiler did not return JSON for ${inputPath}`);
  }

  const outputPath = toOutputPath(inputPath);
  fs.mkdirSync(path.dirname(outputPath), { recursive: true });
  fs.writeFileSync(outputPath, `${compiledJson}\n`);

  const inputLabel = path.relative(projectRoot, inputPath);
  const outputLabel = path.relative(projectRoot, outputPath);
  console.log(`Compiled ${inputLabel} -> ${outputLabel}`);

  for (const warning of warnings) {
    console.warn(`[warn] ${warning}`);
  }
}

function toOutputPath(inputPath) {
  const relativeInputPath = path.relative(storiesRoot, inputPath);
  const outputRelativePath = relativeInputPath.replace(/\.ink$/, '.story.json');
  return path.join(generatedRoot, outputRelativePath);
}

function createFileHandler() {
  const resolveInkFilename = (filename, sourceFilename = null) => {
    const baseDirectory = sourceFilename ? path.dirname(sourceFilename) : storiesRoot;
    return path.resolve(baseDirectory, filename);
  };

  return {
    ResolveInkFilename: resolveInkFilename,
    LoadInkFileContents(filename, sourceFilename = null) {
      const resolvedPath = resolveInkFilename(filename, sourceFilename);
      return fs.readFileSync(resolvedPath, 'utf8');
    },
  };
}

function reportFailure(inputPath, errors) {
  const label = path.relative(projectRoot, inputPath);
  const details = errors.length > 0 ? errors.join('\n') : 'Unknown Ink compilation error.';
  console.error(`Failed to compile ${label}\n${details}`);
  process.exitCode = 1;
}

function generateStoryImageCatalog(storyFiles) {
  const imagePaths = findStoryImages(storyImagesRoot);
  validateStoryImageTags(storyFiles, new Set(imagePaths));

  if (process.exitCode) {
    return;
  }

  const source = [
    '// Generated by scripts/compile-ink.js. Do not edit manually.',
    'export const storyImageSources: Record<string, number> = {',
    ...imagePaths.map((imagePath) => `  ${JSON.stringify(imagePath)}: require(${JSON.stringify(`@/assets/story-images/${imagePath}`)}),`),
    '};',
    '',
  ].join('\n');

  fs.mkdirSync(path.dirname(generatedStoryImagesPath), { recursive: true });
  fs.writeFileSync(generatedStoryImagesPath, source);
  console.log(`Generated ${path.relative(projectRoot, generatedStoryImagesPath)}`);
}

function findStoryImages(directoryPath) {
  if (!fs.existsSync(directoryPath)) {
    return [];
  }

  const imagePaths = [];
  for (const entry of fs.readdirSync(directoryPath, { withFileTypes: true })) {
    const entryPath = path.join(directoryPath, entry.name);

    if (entry.isDirectory()) {
      for (const nestedPath of findStoryImages(entryPath)) {
        imagePaths.push(path.join(entry.name, nestedPath));
      }
      continue;
    }

    if (entry.isFile() && imageExtensions.has(path.extname(entry.name).toLowerCase())) {
      imagePaths.push(entry.name);
    }
  }

  return imagePaths.sort();
}

function validateStoryImageTags(storyFiles, imagePaths) {
  for (const storyFile of storyFiles) {
    const lines = fs.readFileSync(storyFile, 'utf8').split(/\r?\n/);

    for (const [index, line] of lines.entries()) {
      const match = line.match(/^\s*#\s*image\s*:\s*(.*?)\s*$/);
      if (!match) {
        continue;
      }

      const imagePath = match[1];
      if (!imagePath || !imagePaths.has(imagePath)) {
        console.error(
          `${path.relative(projectRoot, storyFile)}:${index + 1} references missing story image "${imagePath}". ` +
            `Add it under ${path.relative(projectRoot, storyImagesRoot)}.`
        );
        process.exitCode = 1;
      }
    }
  }
}
